language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost1.54-dev libboost-regex1.54-dev
  - cmake -G "Unix Makefiles" 

script:
  - make
  - make test

