language: cpp

sudo: false

compiler:
  - clang
#  - gcc

addons:
  apt:
    sources:
      - boost-latest
#      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-dev
      - libboost-regex1.55-dev

install:
  - cmake -G "Unix Makefiles" 

script:
  - make
  - make test

