language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-regex-dev
  - cmake -G "Unix Makefiles" 

script:
  - make
  - make test

